import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { pretendard } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${pretendard.variable}`}>
      <body className="min-h-full flex flex-col">
        <Header />
        <div className="pt-15">{children}</div>
      </body>
    </html>
  );
}
