import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { pretendard } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`h-full antialiased ${pretendard.variable}`}>
      <body className="min-h-full flex flex-col font-pretendard">
        <Header />
        <main className="pt-15 w-full max-w-350 mx-auto">{children}</main>
      </body>
    </html>
  );
}
